name: Bug Report
description: File a bug report to help us improve
title: '[Bug]: '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! ðŸ›

        Before submitting, please search existing issues to avoid duplicates.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of playwright-pageman are you using?
      placeholder: '1.0.0'
      required: true

  - type: input
    id: playwright-version
    attributes:
      label: Playwright Version
      description: What version of Playwright are you using?
      placeholder: '1.41.0'
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: '18.17.0'
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you running?
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure page manager with...
        2. Create/access pages with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please paste your playwright.config.ts and page manager configuration
      render: typescript
      placeholder: |
        // playwright.config.ts
        export default defineConfig({
          use: {
            // your config here
          }
        });

        // test example
        test('page manager usage', async ({ page }) => {
          const pageManager = new PageManager(page);
          // your usage here
        });

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here